### ISSUE TITLE
command 'tsUML.showFile' not found

### ISSUE THREAD

**Issue by initFabian** [myxvisual/vscode-ts-uml#2]
Hi @myxvisual, Awesome extension, it seems really interesting!

Unfortunately, I am unable to get it to work on my vscode instance. However, I was able to get it to work if I bump down the version to v0.0.1

vscode version: 1.30.1
vscode-ts-uml version: 0.0.2
computer: MacOS Mojave, 10.14.2

**Comment by nxpatterns** [comment]
same here,..

**Comment by ssddi456** [comment]
same here...

**Comment by myxvisual** [comment]
@initFabian @webia1 @ssddi456 Hi, sorry for the delay, it’s a busy state recently, fix it now [v0.0.3](https://marketplace.visualstudio.com/items?itemName=myxvisual.vscode-ts-uml).
